misc:
  flag_return_ticks: 6000
  team_buff_ticks: 36000
buffs:
  team:
    NE:
      name: North-East
      location:
        x: 83
        y: 69
        z: -72
        world: world
      potions:
        regeneration:
          amplifier: 0
          duration: 600
      team: ''
      start_ticks: 0
    SW:
      name: South-West
      location:
        x: -81
        y: 69
        z: -70
        world: world
      potions:
        speed:
          amplifier: 1
          duration: 600
      team: ''
      start_ticks: 0
  friend:
    damage_resistance:
      amplifier: 0
      duration: 60
  enemy:
    wither:
      amplifier: 0
      duration: 60
teams:
  red:
    name: Red Team
    chat_color: red
    material: wool
    data: 14
    regions:
    - red_base
    spawn:
      x: 13
      y: 64
      z: 29
      pitch: 10.8826685
      yaw: 181.37572
      world: world
    flags:
      one:
        description: first
        home:
          x: -7
          y: 64
          z: -18
          world: world
        current:
          x: -7
          y: 64
          z: -18
          world: world
      two:
        description: second
        home:
          x: 33
          y: 64
          z: -18
          world: world
        current:
          x: 33
          y: 64
          z: -18
          world: world
    score:
      kills: 0
      steals: 0
      returns: 0
      captures: 0
    members:
      totemo:
        kills: 0
        steals: 0
        returns: 0
        captures: 0
  blue:
    name: Blue Team
    chat_color: aqua
    material: wool
    data: 11
    regions:
    - blue_base
    spawn:
      x: 13
      y: 64
      z: -171
      pitch: 16.53436
      yaw: 1.1937866
      world: world
    flags:
      one:
        description: first
        home:
          x: -7
          y: 64
          z: -123
          world: world
        current:
          x: -7
          y: 64
          z: -123
          world: world
      two:
        description: second
        home:
          x: 33
          y: 64
          z: -123
          world: world
        current:
          x: 33
          y: 64
          z: -123
          world: world
    score:
      kills: 0
      steals: 0
      returns: 0
      captures: 0
    members: {}
