name: CutePVP
main: com.c45y.CutePVP.CutePVP
version: 2.0
softdepend: [WorldGuard]

permissions:
  CutePVP.admin:
    description: Admin with access to all CutePVP commands, not allocated to teams.  A strict superset of the CutePVP.mod permission.
    default: op
    children:
      CutePVP.mod: true
#      Disabled so that staff can play-test.      
#      CutePVP.exempt: true
  CutePVP.mod:
    description: Moderator, not allocated to teams. Can see all team chats.
    default: op
#    Disabled so that staff can play-test.      
#    children:
#      CutePVP.exempt: true
  CutePVP.user:
    description: An ordinary player, allocated to a team.
    default: true
  CutePVP.exempt:
    description: Any player with this permission is not allocated to a team.
commands:
  cutepvp:
    description: Administrative commands.
    permission: CutePVP.admin
    usage: |
           /cutepvp [subcommands]
  g:
    description: Global chat
    permission: CutePVP.user
    usage: |
           /g [message]
  teams:
    description: Lists teams.
    permissions: CutePVP.user
    usage: |
           /teams
  score:
    description: Shows the current scores.
    permissions: CutePVP.user
    usage: |
           /score
  drop:
    description: Drops the flag, if held.
    permissions: CutePVP.user
    usage: |
           /drop
  flag:
    description: Displays the location of the nearest flag owned by your team.
    permissions: CutePVP.user
    usage: |
           /flag

