name: CutePVP
main: com.c45y.CutePVP.CutePVP
version: 2.0
softdepend: [WorldGuard]

permissions:
  CutePVP.admin:
    description: Admin with access to all CutePVP commands, not allocated to teams.  A strict superset of the CutePVP.mod permission.
    default: op
    children:
      CutePVP.mod: true
  CutePVP.mod:
    description: Moderator, not allocated to teams. Can see all team chats.
    default: op
  CutePVP.user:
    description: An ordinary player, allocated to a team.
    default: true
  CutePVP.exempt:
    description: Any player with this permission is not allocated to a team.
commands:
  cutepvp:
    description: Administrative commands.
    permission: CutePVP.admin
    usage: |
           /<command> [subcommands]
  join:
    description: Join a randomly chosen team.
    permission: CutePVP.user
    usage: /<command> 
    
  g:
    description: Global chat.
    permission: CutePVP.user
    usage: /<command> [message]
  teams:
    description: Lists teams.
    permissions: CutePVP.user
    usage: /<command>
  score:
    description: Shows the current scores.
    permissions: CutePVP.user
    usage: /<command>
  drop:
    description: Drops the flag, if held.
    permissions: CutePVP.user
    usage: /<command>
  flag:
    description: Displays the location of the nearest flag owned by your team.
    permissions: CutePVP.user
    usage: /<command>
  testblock:
    description: Toggles testing of power blocks. When testing is enabled, hostile blocks placed by the player's own team are still effective.
    permissions: CutePVP.user
    usage: /<command>

